services:
  - type: web
    name: fitflix-website
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx vite preview --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
