services:
  - type: static_site
    name: fitflix-website
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
