services:
  - type: web
    name: fitflix-web
    buildCommand: npm ci && npm run build:prod && cp public/_redirects dist/
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    
    # SPA routing - serve index.html for all routes
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
    # Add headers for SPA routing
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: "production"
      - key: VITE_API_BASE_URL
        value: "https://fitflix-backend-avxt.onrender.com"
      - key: VITE_ENABLE_PWA
        value: "true"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
      - key: VITE_ENABLE_ERROR_TRACKING
        value: "true"
