services:
  - type: web
    name: fitflix-web
    buildCommand: npm ci && npm run build:prod
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: "production"
      - key: VITE_API_BASE_URL
        value: "https://fitflix-backend-api.onrender.com"
      - key: VITE_ENABLE_PWA
        value: "true"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
      - key: VITE_ENABLE_ERROR_TRACKING
        value: "true"
